parameters:
    app_bundle.packageName: Twilio
    app_bundle.metadata:
        package: "%app_bundle.packageName%"
        tagline: Twilio API Wrapper
        description: This block allows you to make voice calls, send sms or mms.
        image: https://www.twilio.com/marketing/bundles/marketing/img/favicons/favicon.ico
        keywords:
          - API
          - call
          - marketing
          - message
          - messaging
          - mms
          - phone
          - sms
          - text
          - voice
        repo: https://github.com/RapidSoftwareSolutions/Marketplace-Twilio-Package
        accounts:
          domain: twilio.com
          credentials:
            - accountSid
            - accountToken
        events:
        -
          name: webhookEvent
          description: This method is called every time a Twilio event occurs
          payload:
            body: modified message text
            from: modified from value
            attributes: '{"key" : "value"}'
          steps:
          -
            Navigate to https://www.twilio.com/console/phone-numbers/incoming
          -
            Create or select a phone number you want to use
          -
            Configure the events to use webhooks with the following URL: __WEBHOOK_URL__
          args:
          -
            name: token
            type: string
            info: Token sent on each message
            required: false
        blocks:
        -
          name: makeCall
          description: This block allows you to make voice calls
          args:
            -
              name: accountSid
              type: credentials
              info: "A 34 character string that uniquely identifies this account."
              required: true
            -
              name: accountToken
              type: credentials
              info: "The authorization token for this account."
              required: true
            -
              name: from
              type: String
              info: "The phone number or client identifier to use as the caller id. If using a phone number, it must be a Twilio number or a Verified outgoing caller id for your account."
              required: true
            -
              name: to
              type: String
              info: "The phone number, SIP address or client identifier to call."
              required: true
            -
              name: url
              type: String
              info: "The fully qualified URL that should be consulted when the call connects. Just like when you set a URL on a phone number for handling inbound calls. See the Url Parameter section below for more details."
              required: true
            -
              name: applicationSid
              type: String
              info: "Required if url not provided. The 34 character sid of the application Twilio should use to handle this phone call. If this parameter is present, Twilio will ignore all of the voice URLs passed and use the URLs set on the application."
              required: false
            -
              name: method
              type: String
              info: "The HTTP method Twilio should use when making its request to the above Url parameter's value. Defaults to POST. If an ApplicationSid parameter is present, this parameter is ignored."
              required: false
            -
              name: fallbackUrl
              type: String
              info: "A URL that Twilio will request if an error occurs requesting or executing the TwiML at Url. If an ApplicationSid parameter is present, this parameter is ignored."
              required: false
            -
              name: fallbackMethod
              type: String
              info: "The HTTP method that Twilio should use to request the FallbackUrl. Must be either GET or POST. Defaults to POST. If an ApplicationSid parameter is present, this parameter is ignored."
              required: false
            -
              name: statusCallback
              type: String
              info: "A URL that Twilio will send asynchronous webhook requests to on every call event specified in the StatusCallbackEvent parameter. If no event is present, Twilio will send completed by default. If an ApplicationSid parameter is present, this parameter is ignored. URLs must contain a valid hostname."
              required: false
            -
              name: statusCallbackMethod
              type: String
              info: "The HTTP method Twilio should use when requesting the above URL. Defaults to POST. If an ApplicationSid parameter is present, this parameter is ignored."
              required: false
            -
              name: statusCallbackEvent
              type: String
              info: "The call progress events that Twilio will send webhooks on. Available values are initiated, ringing, answered, and completed."
              required: false
            -
              name: sendDigits
              type: String
              info: "A string of keys to dial after connecting to the number, maximum of 32 digits."
              required: false
            -
              name: timeout
              type: String
              info: "The integer number of seconds that Twilio should allow the phone to ring before assuming there is no answer."
              required: false
            -
              name: record
              type: Boolean
              info: "Set this parameter to 'true' to record the entirety of a phone call."
              required: false
            -
              name: recordingChannels
              type: Select
              options:
                -
                  mono
                -
                  dual
              info: "Mono or dual. Set this parameter to specify the number of channels in the final recording. Defaults to 'mono'."
              required: false
            -
              name: recordingStatusCallback
              type: String
              info: "The recordingStatusCallback attribute takes an absolute URL as an argument."
              required: false
            -
              name: recordingStatusCallbackMethod
              type: String
              info: "The HTTP method Twilio should use when requesting the above URL. Defaults to POST"
              required: false
          callbacks:
            -
              name: error
              info: "Error"
            -
              name: success
              info: "Success"
        -
          name: sendSms
          description: This block allows you to send sms.
          args:
            -
              name: accountSid
              type: credentials
              info: "A 34 character string that uniquely identifies this account."
              required: true
            -
              name: accountToken
              type: credentials
              info: "The authorization token for this account."
              required: true
            -
              name: from
              type: String
              info: "A Twilio phone number (in E.164 format) or alphanumeric sender ID enabled for the type of message you wish to send. Phone numbers or short codes purchased from Twilio work here. You cannot (for example) spoof messages from your own cell phone number."
              required: true
            -
              name: messagingServiceSid
              type: String
              info: "Required if from not provided. The 34 character unique id of the Messaging Service you want to associate with this Message. Set this parameter to use the Messaging Service Settings and Copilot Features you have configured. When only this parameter is set, Twilio will use your enabled Copilot Features to select the From phone number for delivery."
              required: false
            -
              name: to
              type: String
              info: "The destination phone number. Format with a '+' and country code e.g., +16175551212 (E.164 format)."
              required: true
            -
              name: body
              type: String
              info: "The text of the message you want to send, limited to 1600 characters."
              required: true
            -
              name: statusCallback
              type: String
              info: "A URL that Twilio will POST to each time your message status changes to one of the following: queued, failed, sent, delivered, or undelivered."
              required: false
            -
              name: applicationSid
              type: String
              info: "Twilio will POST MessageSid as well as MessageStatus=sent or MessageStatus=failed to the URL in the MessageStatusCallback property of this Application."
              required: false
            -
              name: maxPrice
              type: String
              info: "The total maximum price in US dollars acceptable for the message to be delivered."
              required: false
            -
              name: provideFeedback
              type: String
              info: "Set this value to true if you are sending messages that have a trackable user action and you intend to confirm delivery of the message using the Message Feedback API. This parameter is set to false by default."
              required: false
          callbacks:
            -
              name: error
              info: "Error"
            -
              name: success
              info: "Success"
        -
          name: sendMms
          description: This block allows you to send mms.
          args:
            -
              name: accountSid
              type: credentials
              info: "A 34 character string that uniquely identifies this account."
              required: true
            -
              name: accountToken
              type: credentials
              info: "The authorization token for this account."
              required: true
            -
              name: from
              type: String
              info: "A Twilio phone number (in E.164 format) or alphanumeric sender ID enabled for the type of message you wish to send. Phone numbers or short codes purchased from Twilio work here. You cannot (for example) spoof messages from your own cell phone number."
              required: true
            -
              name: messagingServiceSid
              type: String
              info: "Required if from not provided. The 34 character unique id of the Messaging Service you want to associate with this Message. Set this parameter to use the Messaging Service Settings and Copilot Features you have configured. When only this parameter is set, Twilio will use your enabled Copilot Features to select the From phone number for delivery."
              required: false
            -
              name: to
              type: String
              info: "The destination phone number. Format with a '+' and country code e.g., +16175551212 (E.164 format)."
              required: true
            -
              name: mediaUrl
              type: String
              info: "The URL of the media you wish to send out with the message. gif , png and jpeg content is currently supported and will be formatted correctly on the recipient's device."
              required: true
            -
              name: statusCallback
              type: String
              info: "A URL that Twilio will POST to each time your message status changes to one of the following: queued, failed, sent, delivered, or undelivered."
              required: false
            -
              name: applicationSid
              type: String
              info: "Twilio will POST MessageSid as well as MessageStatus=sent or MessageStatus=failed to the URL in the MessageStatusCallback property of this Application."
              required: false
            -
              name: maxPrice
              type: String
              info: "The total maximum price in US dollars acceptable for the message to be delivered."
              required: false
            -
              name: provideFeedback
              type: String
              info: "Set this value to true if you are sending messages that have a trackable user action and you intend to confirm delivery of the message using the Message Feedback API. This parameter is set to false by default."
              required: false
          callbacks:
            -
              name: error
              info: "Error"
            -
              name: success
              info: "Success"

services:
    app_bundle.package_abstract:
        class: TwilioBundle\Utils\TwilioAbstaract
        abstract: true
        arguments: ["@request_stack"]
    app_bundle.call:
        class: TwilioBundle\Utils\Call
        parent: app_bundle.package_abstract
    app_bundle.sms:
        class: TwilioBundle\Utils\Sms
        parent: app_bundle.package_abstract
    app_bundle.mms:
        class: TwilioBundle\Utils\Mms
        parent: app_bundle.package_abstract
